/* global React */
// Code view — dynamically generated code from the project's pages.

// --- Pure code-generation helpers (no React deps) ---

function buildChildMap(connections) {
  const m = {};
  connections.filter(c => c.kind === 'child').forEach(c => {
    if (!m[c.from]) m[c.from] = [];
    m[c.from].push(c.to);
  });
  return m;
}
window.buildChildMap = buildChildMap;

function pascalName(s) {
  const out = (s || '').replace(/[^a-zA-Z0-9]+/g, ' ').trim().split(' ')
    .filter(Boolean).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join('');
  return out || 'Page';
}

function nodeToJSX(node, allNodes, childMap, depth) {
  const children = (childMap[node.id] || [])
    .map(id => allNodes.find(n => n.id === id)).filter(Boolean);
  const indent = '  '.repeat(depth);
  const lc = node.layout ? node.layout.toLowerCase().replace(' ', '-') : null;
  const tokens = [];

  tokens.push({ t: indent + '<', c: 'var(--text-secondary)' });
  tokens.push({ t: node.name, c: 'var(--green-base)' });
  if (lc) {
    tokens.push({ t: ' layout=', c: 'var(--text-secondary)' });
    tokens.push({ t: `"${lc}"`, c: 'var(--amber-base)' });
  }
  if (node.gap) {
    tokens.push({ t: ' gap=', c: 'var(--text-secondary)' });
    tokens.push({ t: `{${node.gap}}`, c: 'var(--amber-base)' });
  }

  if (children.length === 0) {
    tokens.push({ t: '>', c: 'var(--text-secondary)' });
    if (node.label) tokens.push({ t: node.label, c: 'var(--text-primary)' });
    tokens.push({ t: `</${node.name}>\n`, c: 'var(--text-secondary)' });
  } else {
    tokens.push({ t: '>\n', c: 'var(--text-secondary)' });
    children.forEach(child => tokens.push(...nodeToJSX(child, allNodes, childMap, depth + 1)));
    tokens.push({ t: indent + `</${node.name}>\n`, c: 'var(--text-secondary)' });
  }
  return tokens;
}

function generatePageCode(nodes, connections, componentName) {
  const childMap = buildChildMap(connections);
  const childIds = new Set(connections.filter(c => c.kind === 'child').map(c => c.to));
  const roots = nodes.filter(n => !childIds.has(n.id));

  const tokens = [
    { t: 'import', c: 'var(--blue-base)' },
    { t: ' React ', c: 'var(--text-primary)' },
    { t: 'from', c: 'var(--blue-base)' },
    { t: " 'react';\n\n", c: 'var(--amber-base)' },
    { t: 'export function ', c: 'var(--text-muted)' },
    { t: componentName, c: 'var(--blue-base)' },
    { t: '() {\n', c: 'var(--text-secondary)' },
    { t: '  return (\n', c: 'var(--text-muted)' },
  ];

  if (roots.length === 0) {
    tokens.push({ t: '    {/* no root nodes */}\n', c: 'var(--text-muted)' });
  } else if (roots.length === 1) {
    tokens.push(...nodeToJSX(roots[0], nodes, childMap, 4));
  } else {
    tokens.push({ t: '    <>\n', c: 'var(--text-secondary)' });
    roots.forEach(r => tokens.push(...nodeToJSX(r, nodes, childMap, 6)));
    tokens.push({ t: '    </>\n', c: 'var(--text-secondary)' });
  }

  tokens.push(
    { t: '  );\n', c: 'var(--text-muted)' },
    { t: '}', c: 'var(--text-secondary)' },
  );
  return tokens;
}

function generateCssTokens(nodes) {
  const tokens = [{ t: '/* Generated by Lattice */\n\n', c: 'var(--text-muted)' }];
  const seen = new Set();
  nodes.forEach(n => {
    const cls = n.name.replace(/([A-Z])/g, m => '-' + m.toLowerCase()).replace(/^-/, '');
    if (seen.has(cls)) return;
    seen.add(cls);
    tokens.push({ t: `.${cls}`, c: 'var(--blue-base)' });
    tokens.push({ t: ' {\n', c: 'var(--text-secondary)' });
    tokens.push({ t: `  width: `, c: 'var(--text-muted)' }, { t: `${n.w}px`, c: 'var(--amber-base)' }, { t: ';\n', c: 'var(--text-muted)' });
    tokens.push({ t: `  height: `, c: 'var(--text-muted)' }, { t: `${n.h}px`, c: 'var(--amber-base)' }, { t: ';\n', c: 'var(--text-muted)' });
    if (n.layout) {
      const lc = n.layout.toLowerCase();
      if (lc.includes('flex')) {
        tokens.push({ t: `  display: flex;\n  flex-direction: `, c: 'var(--text-muted)' });
        tokens.push({ t: lc.includes('row') ? 'row' : 'column', c: 'var(--amber-base)' });
        tokens.push({ t: ';\n', c: 'var(--text-muted)' });
      } else if (lc === 'grid') {
        tokens.push({ t: `  display: `, c: 'var(--text-muted)' }, { t: 'grid', c: 'var(--amber-base)' }, { t: ';\n', c: 'var(--text-muted)' });
      }
    }
    if (n.gap) {
      tokens.push({ t: `  gap: `, c: 'var(--text-muted)' }, { t: `${n.gap}px`, c: 'var(--amber-base)' }, { t: ';\n', c: 'var(--text-muted)' });
    }
    if (n.fillColor) {
      tokens.push({ t: `  background: `, c: 'var(--text-muted)' }, { t: n.fillColor, c: 'var(--amber-base)' }, { t: ';\n', c: 'var(--text-muted)' });
    }
    tokens.push({ t: '}\n\n', c: 'var(--text-secondary)' });
  });
  return tokens;
}

function tokensToText(tokens) { return tokens.map(t => t.t).join(''); }

function downloadText(filename, text) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// --- Component ---

function CodePanel({ pages, activePageId }) {
  const { Tag, Button } = window.LatticeDesignSystem_e801cb;
  const [copied, setCopied] = React.useState(false);

  // Build one file per page (unique component names) + a shared styles.css
  const files = React.useMemo(() => {
    const used = {};
    const out = pages.map(p => {
      let base = pascalName(p.name);
      if (used[base]) { used[base]++; base = base + used[base]; } else { used[base] = 1; }
      return { pageId: p.id, name: base + '.tsx', tokens: generatePageCode(p.nodes, p.connections, base) };
    });
    const allNodes = pages.flatMap(p => p.nodes);
    out.push({ pageId: null, name: 'styles.css', tokens: generateCssTokens(allNodes) });
    return out;
  }, [pages]);

  const defaultFile = (files.find(f => f.pageId === activePageId) || files[0]).name;
  const [fileName, setFileName] = React.useState(defaultFile);
  const active = files.find(f => f.name === fileName) || files.find(f => f.name === defaultFile) || files[0];

  const handleCopy = () => {
    const text = tokensToText(active.tokens);
    const doFallback = () => {
      const ta = document.createElement('textarea');
      ta.value = text; document.body.appendChild(ta); ta.select();
      document.execCommand('copy'); document.body.removeChild(ta);
    };
    try {
      if (navigator.clipboard) navigator.clipboard.writeText(text).catch(doFallback);
      else doFallback();
    } catch { doFallback(); }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => downloadText(active.name, tokensToText(active.tokens));
  const handleExportAll = () => files.forEach(f => downloadText(f.name, tokensToText(f.tokens)));

  return (
    <div style={{ flex: 1, minWidth: 0, display: 'flex', background: 'var(--bg-app)' }}>
      {/* File rail */}
      <div style={{ width: 200, flex: 'none', borderRight: '1px solid var(--border-subtle)', padding: 10, background: 'var(--surface)', overflow: 'auto' }}>
        <div style={{ fontSize: 10, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.12em', color: 'var(--text-muted)', margin: '4px 6px 10px' }}>Generated</div>
        {files.map(f => (
          <button key={f.name} type="button" onClick={() => setFileName(f.name)} style={{
            display: 'flex', alignItems: 'center', gap: 8, width: '100%', padding: '7px 8px',
            background: f.name === active.name ? 'var(--surface-hover)' : 'transparent', border: 0,
            color: f.name === active.name ? 'var(--text-primary)' : 'var(--text-secondary)',
            cursor: 'pointer', fontSize: 12.5, fontFamily: 'var(--font-mono)', textAlign: 'left',
          }}>
            <i data-lucide={f.name.endsWith('.css') ? 'palette' : 'file-code'} style={{ width: 13, height: 13, opacity: 0.7 }}></i>{f.name}
          </button>
        ))}
      </div>

      {/* Editor area */}
      <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 16px', borderBottom: '1px solid var(--border-subtle)' }}>
          <span style={{ fontSize: 12.5, fontFamily: 'var(--font-mono)', color: 'var(--text-primary)' }}>{active.name}</span>
          <Tag shape="pill">{active.name.endsWith('.css') ? 'CSS' : 'React + TS'}</Tag>
          <div style={{ marginLeft: 'auto', display: 'flex', gap: 8 }}>
            <Button variant="ghost" size="sm" onClick={handleCopy} iconLeft={<i key={copied ? 'c' : 'o'} data-lucide={copied ? 'check' : 'copy'}></i>}>
              {copied ? 'Copied' : 'Copy'}
            </Button>
            <Button variant="ghost" size="sm" onClick={handleExport} iconLeft={<i data-lucide="download"></i>}>Export</Button>
            <Button variant="outline" size="sm" onClick={handleExportAll} iconLeft={<i data-lucide="folder-down"></i>}>Export all</Button>
          </div>
        </div>
        <pre style={{ margin: 0, padding: '18px 20px', flex: 1, overflow: 'auto', fontFamily: 'var(--font-mono)', fontSize: 13, lineHeight: 1.7, background: 'var(--surface-inset)' }}>
          <code style={{ whiteSpace: 'pre-wrap' }}>
            {active.tokens.map((s, i) => <span key={i} style={{ color: s.c }}>{s.t}</span>)}
          </code>
        </pre>
      </div>
    </div>
  );
}
window.CodePanel = CodePanel;
